name: Enhancement
description: If you have issue with something
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        General enhancement idea what we could implement.
        Or something we could make easier to use so DX increases.
  - type: input
    id: what
    attributes:
      label: What could be improved
      description: If there is some specific thing
      placeholder: ex. js-resolvers
    validations:
      required: false

  - type: textarea
    id: what-change
    attributes:
      label: Which kinda change
      description: What you would change?
      placeholder: |
        xxx produces different result on local-api and AppSync.

        or

        yyy is hard to use, can you make it simpler to use.
        Here is how I would like to use it:
        ...
    validations:
      required: true
