name: Slack test action
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to dev/tst/stg/prd
        required: true
jobs:
  post_message:
    runs-on: ubuntu-latest
    steps:
      - name: Post message
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secret.SLACK_OAUTH }}
          payload: |
            channel: C092ZCWEL75
            text: "Testing slack output"
            attachments:
            - fields:
              - title: "Testing fields"
                short: true
                value: "Completed"
