name: Testing find changd files
on:
  workflow_dispatch:

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Get changed files
        run: |
          ./test-changed-files.yml
