name: Testing find changd files
on:
  workflow_dispatch:
  pull_request:

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: ./get-changed-sceptre-files
        with:
          github-token: ${{ github.token }}
          owner: ${{ github.owner }}
          repository: ${{ github.repository }}
          pr: ${{ github.event.number }}
