name: Testing find changd files
on:
  workflow_dispatch:
  pull_request:

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Get changed files
        run: |
          get-sceptre-files.ts
        with:
          token: ${{ github.token }}
          owner: ${{ github.owner }}
          repository: ${{ github.repository }}
          pr: ${{ github.event.number }}
